development:
  adapter: postgresql
  encoding: unicode
  database: murder_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: murder_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: murder_production
  pool: 5
  username: postgres
  password:
